#include "Item.h"

ItemData::ItemData(EItemID id, std::string name, std::string description, int purchasePrice, bool isConsumable, EItemEffectType effectType, int effectValue)
    : id(id), name(name), description(description), purchasePrice(purchasePrice), isConsumable(isConsumable), effectType(effectType), effectValue(effectValue)
{
}

const std::map<EItemID, ItemData> ITEM_TABLE = {
    // ========== Consumable Items ==========

    {EItemID::HP_POTION, ItemData(EItemID::HP_POTION,
                                  "HP 포션",
                                  "플레이어의 체력을 회복한다.",
                                  30,
                                  true,
                                  EItemEffectType::HEAL_HP,
                                  50)},
    {EItemID::POWER_POTION, ItemData(EItemID::POWER_POTION,
                                     "공격력 증가 포션",
                                     "플레이어의 공격력을 이번 전투 동안만 증가시킨다.",
                                     40,
                                     true,
                                     EItemEffectType::BUFF_POWER,
                                     10)},
    // ========== Crafting Ingredient Items ==========

    {EItemID::BOTTLE, ItemData(EItemID::BOTTLE,
                               "병",
                               "포션을 담을 수 있는 빈 유리병.",
                               10)},
    {EItemID::WATER, ItemData(EItemID::WATER,
                              "물",
                              "포션 제작에 사용되는 깨끗한 물.",
                              5)},

    // ========== Monster Drop Items ==========

    // 슬라임
    {EItemID::SLIME_JELLY, ItemData(EItemID::SLIME_JELLY,
                                    "슬라임 젤리",
                                    "말랑한 슬라임의 잔해. 약한 회복 재료로 쓰임.",
                                    7)},
    {EItemID::SLIME_CORE, ItemData(EItemID::SLIME_CORE,
                                   "슬라임 핵",
                                   "희미한 마력이 남아 있는 작은 핵.",
                                   13)},
    {EItemID::SLIME_CLEAR_WATER_DROP, ItemData(EItemID::SLIME_CLEAR_WATER_DROP,
                                               "맑은 물방울",
                                               "정제된 슬라임에게서만 얻는 깨끗한 물방울.",
                                               20)},

    // 고블린
    {EItemID::GOBLIN_EAR, ItemData(EItemID::GOBLIN_EAR,
                                   "고블린 귀",
                                   "고블린을 처치했다는 증표로 쓰임.",
                                   13)},
    {EItemID::GOBLIN_DAGGER_FRAGMENT, ItemData(EItemID::GOBLIN_DAGGER_FRAGMENT,
                                               "낡은 단검 조각",
                                               "고블린이 쓰던 조잡한 단검의 파편.",
                                               25)},
    {EItemID::GOBLIN_COIN_POUCH, ItemData(EItemID::GOBLIN_COIN_POUCH,
                                          "해진 동전 주머니",
                                          "몇 푼의 동전이 남아 있는 작은 주머니.",
                                          37)},

    // 스켈레톤
    {EItemID::SKELETON_BONE, ItemData(EItemID::SKELETON_BONE,
                                      "낡은 뼈",
                                      "오래된 언데드의 뼈 조각.",
                                      20)},
    {EItemID::SKELETON_RUSTED_BUCKLE, ItemData(EItemID::SKELETON_RUSTED_BUCKLE,
                                               "녹슨 버클",
                                               "갑옷에 달려 있던 낡은 금속 버클.",
                                               33)},
    {EItemID::SKELETON_CURSED_TOOTH, ItemData(EItemID::SKELETON_CURSED_TOOTH,
                                              "저주받은 이빨",
                                              "약한 어둠의 기운이 남아 있는 이빨.",
                                              50)},

    // 좀비
    {EItemID::ZOMBIE_ROTTEN_FLESH, ItemData(EItemID::ZOMBIE_ROTTEN_FLESH,
                                            "썩은 살점",
                                            "상태는 나쁘지만 암흑 연금 재료가 됨.",
                                            25)},
    {EItemID::ZOMBIE_GRAVE_CLOTH, ItemData(EItemID::ZOMBIE_GRAVE_CLOTH,
                                           "무덤 천 조각",
                                           "흙과 음기가 배어 있는 천 조각.",
                                           42)},
    {EItemID::ZOMBIE_PLAGUE_FANG, ItemData(EItemID::ZOMBIE_PLAGUE_FANG,
                                           "역병 이빨",
                                           "독성 재료로 사용할 수 있는 좀비의 이빨.",
                                           63)},

    // 코볼트
    {EItemID::KOBOLD_FANG, ItemData(EItemID::KOBOLD_FANG,
                                    "코볼트 송곳니",
                                    "야수 같은 코볼트의 날카로운 이빨.",
                                    42)},
    {EItemID::KOBOLD_CLAW, ItemData(EItemID::KOBOLD_CLAW,
                                    "코볼트 발톱",
                                    "가죽 가공에 쓸 수 있는 단단한 발톱.",
                                    53)},
    {EItemID::KOBOLD_LEATHER, ItemData(EItemID::KOBOLD_LEATHER,
                                       "코볼트 가죽",
                                       "질긴 가죽 조각. 방어구 재료로 쓰임.",
                                       67)},
    {EItemID::KOBOLD_TRIBAL_PENDANT, ItemData(EItemID::KOBOLD_TRIBAL_PENDANT,
                                              "부족의 펜던트",
                                              "코볼트 부족의 문양이 새겨진 장신구.",
                                              92)},

    // 골렘
    {EItemID::GOLEM_STONE_FRAGMENT, ItemData(EItemID::GOLEM_STONE_FRAGMENT,
                                             "골렘 돌 조각",
                                             "마력이 깃든 단단한 돌 조각.",
                                             75)},
    {EItemID::GOLEM_MAGIC_CORE, ItemData(EItemID::GOLEM_MAGIC_CORE,
                                         "골렘 마력핵",
                                         "골렘을 움직이게 하던 마력의 중심부.",
                                         125)},
    {EItemID::GOLEM_IRON_ARM, ItemData(EItemID::GOLEM_IRON_ARM,
                                       "철제 팔 파편",
                                       "무겁고 단단한 골렘의 팔 조각.",
                                       150)},
    {EItemID::GOLEM_GEMSTONE, ItemData(EItemID::GOLEM_GEMSTONE,
                                       "마력 보석",
                                       "골렘 내부에서 발견되는 빛나는 보석.",
                                       200)},

    // 방황하는 갑옷
    {EItemID::WANDERING_ARMOR_CRACKED_ARMOR_PLATE, ItemData(EItemID::WANDERING_ARMOR_CRACKED_ARMOR_PLATE,
                                                            "금 간 갑옷판",
                                                            "오래된 갑옷의 단단한 금속판.",
                                                            133)},
    {EItemID::WANDERING_ARMOR_CURSED_HELM_FRAGMENT, ItemData(EItemID::WANDERING_ARMOR_CURSED_HELM_FRAGMENT,
                                                             "저주받은 투구 조각",
                                                             "불길한 기운이 남아 있는 투구 파편.",
                                                             175)},
    {EItemID::WANDERING_ARMOR_RUSTED_SWORD_FRAGMENT, ItemData(EItemID::WANDERING_ARMOR_RUSTED_SWORD_FRAGMENT,
                                                              "녹슨 검 조각",
                                                              "검은 녹이 슨 검날 조각.",
                                                              208)},
    {EItemID::WANDERING_ARMOR_NOBLE_CREST, ItemData(EItemID::WANDERING_ARMOR_NOBLE_CREST,
                                                    "낡은 귀족 문장",
                                                    "과거 주인의 신분을 보여 주는 문장.",
                                                    250)},
    {EItemID::WANDERING_ARMOR_SOUL_STEEL, ItemData(EItemID::WANDERING_ARMOR_SOUL_STEEL,
                                                   "혼의 강철",
                                                   "갑옷을 움직이게 하던 희귀한 금속.",
                                                   317)},

    // 드라큘라
    {EItemID::DRACULA_BAT_WING, ItemData(EItemID::DRACULA_BAT_WING,
                                         "흡혈박쥐 날개",
                                         "어둠의 기운이 남은 날개 조각.",
                                         200)},
    {EItemID::DRACULA_BLOOD_VIAL, ItemData(EItemID::DRACULA_BLOOD_VIAL,
                                           "진홍의 혈액병",
                                           "강한 생명력이 응축된 피가 담긴 병.",
                                           267)},
    {EItemID::DRACULA_VAMPIRE_FANG, ItemData(EItemID::DRACULA_VAMPIRE_FANG,
                                             "흡혈귀 송곳니",
                                             "매우 날카롭고 희귀한 송곳니.",
                                             333)},
    {EItemID::DRACULA_DARK_CAPE_CLOTH, ItemData(EItemID::DRACULA_DARK_CAPE_CLOTH,
                                                "검은 망토 천",
                                                "마력이 스며든 고급 천 조각.",
                                                383)},
    {EItemID::DRACULA_MOONSTONE, ItemData(EItemID::DRACULA_MOONSTONE,
                                          "월광석",
                                          "달빛 아래에서 은은하게 빛나는 보석.",
                                          467)},

    // 레드 드래곤
    {EItemID::RED_DRAGON_SCALE, ItemData(EItemID::RED_DRAGON_SCALE,
                                         "붉은 용비늘",
                                         "불에 강한 붉은 비늘. 고급 방어구 재료.",
                                         695)},
    {EItemID::RED_DRAGON_CLAW, ItemData(EItemID::RED_DRAGON_CLAW,
                                        "붉은 용발톱",
                                        "단단하고 날카로운 거대한 발톱.",
                                        888)},
    {EItemID::RED_DRAGON_FANG, ItemData(EItemID::RED_DRAGON_FANG,
                                        "붉은 용송곳니",
                                        "강력한 무기 제작 재료.",
                                        1055)},
    {EItemID::RED_DRAGON_HORN, ItemData(EItemID::RED_DRAGON_HORN,
                                        "붉은 용뿔",
                                        "강한 마력이 담긴 희귀한 뿔.",
                                        1250)},
    {EItemID::RED_DRAGON_DRAGON_WING_MEMBRANE, ItemData(EItemID::RED_DRAGON_DRAGON_WING_MEMBRANE,
                                                        "용 날개막",
                                                        "불에 잘 타지 않는 질긴 막.",
                                                        1388)},
    {EItemID::RED_DRAGON_FLAME_ORB, ItemData(EItemID::RED_DRAGON_FLAME_ORB,
                                             "화염구",
                                             "꺼지지 않는 불꽃을 품은 마력 구체.",
                                             1805)},
    {EItemID::RED_DRAGON_DRAGON_HEART, ItemData(EItemID::RED_DRAGON_DRAGON_HEART,
                                                "용의 심장",
                                                "붉은 용의 힘이 응축된 최고급 재료.",
                                                2778)},
};
